const services = {
    authService: require('./auth'),
    userService: require('./user'),
    dishService: require('./dish'),
    dishTypeService: require('./dishtype'),
    cartService: require('./cart'),
    rateService: require('./rate'),
    paymentService: require('./payment'),
    orderService: require('./order'),
    orderDetailService: require('./orderdetail'),
    blogService: require('./blog'),
    commentService: require('./comment'),
    commentRepService: require('./commentrep'),
    followService: require('./follow'),
    locationService: require('./location'),
    addressService: require('./address'),
    adminService: require('./admin'),
    roleService: require('./role'),
    permissService: require('./permiss'),
    trackerService: require('./tracker'),
    scheduleService: require('./schedule'),
    analyticService: require('./analytic'),
    reasonService: require('./reason'),
    toppingService: require('./topping'),
};

module.exports = services;