const controller = {
    userController: require('./user'),
    authController: require('./auth'),
    dishController: require('./dish'),
    dishTypeController: require('./dishType'),
    cartController: require('./cart'),
    rateController: require('./rate'),
    paymentController: require('./payment'),
    orderController: require('./order'),
    orderDetailController: require('./orderdetail'),
    blogController: require('./blog'),
    commentController: require('./comment'),
    commentRepController: require('./commentrep'),
    notifController: require('./notification'),
    followController: require('./follow'),
    locationController: require('./location'),
    addressController: require('./address'),
    adminController: require('./admin'),
    roleController: require('./role'),
    permissController: require('./permiss'),
    messageController: require('./message'),
    converController: require('./conver'),
    trackerController: require('./tracker'),
}

module.exports = controller;