const ProductActionTypes = {
    INIT_PRODUCTS: 'INIT_PRODUCTS',
    GET_PRODUCTS: 'GET_PRODUCTS',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    UNABLE_PRODUCT: 'UNABLE_PRODUCT',
    RECOVER_PRODUCT: 'RECOVER_PRODUCT',
}

export default ProductActionTypes;