const StaffActionTypes = {
    INIT_STAFFS: 'INIT_STAFFS',
    GET_STAFFS: 'GET_STAFFS',
    CREATE_STAFF: 'CREATE_STAFF',
    UPDATE_STAFF: 'UPDATE_STAFF',
    UNABLE_STAFF: 'UNABLE_STAFF',
    RECOVER_STAFF: 'RECOVER_STAFF',
}

export default StaffActionTypes;